services:
  api:
    build:
      context: ./BackendNailShop
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User Id=sa;Password=YourStrong@Passw0rd;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqlserverdata:/var/opt/mssql

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  sqlserverdata:
